version: '3'

services:

    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root

    user-service:
        build: ./user-service
        ports:
          - 9001:9001