version: '3'

services:

    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: FunProjects0!
      ports: 
        - 3306:3306

    user-service:
        build: ./user-service
        ports:
          - 9001:9001