version: '3'

services:

    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: FunProjects0!
      ports: 
        - 3306:3306

    user-service:
        build: ./user-service
        ports:
          - 9001:9001

    product-service:
      build: ./product-service
      ports:
        - 9002:9002

    shop-service:
      build: ./shop-service
      ports:
        - 9003:9003

    auth-service:
      build: ./auth-service
      ports:
        - 9004:9004
